export enum colorsEnum {
  transparent = "transparent",
  black = "black",
  white = "white",
  background = "background",
  borderColor = "borderColor",
  borderColorDark = "borderColorDark",
  inputColor = "inputColor",
  neutral = "neutral",
  // lightAccent = 'lightAccent',
  // accent = 'accent',
  // neutral0 = 'neutral0',
  // neutral1 = 'neutral1',
  // neutral2 = 'neutral2',
  // neutral3 = 'neutral3',
  // neutral4 = 'neutral4',
  // neutral5 = 'neutral5',
  // neutral6 = 'neutral6',
  // info = 'info',
  // error = 'error',
  // warning = 'warning',
  // success = 'success',
}
export const colors: { [key in colorsEnum]: string } = {
  black: "#222222",
  transparent: "transparent",
  white: "#fff",
  background: "#f7f7f9",
  inputColor: "#f7f7f9",
  neutral: "#6e6969",
  borderColor: "#cccdcd",
  borderColorDark: "#b9b9b9",
};
